### ISSUE TITLE
As an Admin, I want to be able to search for invoices by Invoice ID, Customer ID or Order ID to quickly find an invoice.

### ISSUE THREAD

**Issue by JohnoAlm** [KYH-Net23/InvoiceProvider#31]
**Made by Hossén & Oliver**

# Acceptance Criteria:

- [ ] Only an admin should be able to view/search invoices.
- [ ] There should be a search bar.
- [ ] You should be able to search by Invoice ID, Customer ID, or Order ID.
- [ ] There should be a filter to choose what to search by.
- [ ] The search should be triggered by pressing the “Search” button or hitting the “Enter” key.
- [ ] There should be a “Reset” button that resets the search and filter options and shows the default list.
- [ ] The search should not continue if the search bar is empty or it should go to default and show all invoices.
- [ ] Searching for an ID should redirect to that invoice’s page if there is an invoice with that ID. As in, if I search for Invoice ID “213” it will redirect me to its detailed page.

# Tasks:
- [ ] Implement UI/frontend.
  - [ ] Task 1: Create a search bar with a search button.
  - [ ] Task 2: Create a reset button.
  - [ ] Task 3: Implement redirection.
- [ ] Task 4: Implement search query logic.
- [ ] Task 5: KYH-Net23/AdminInvoiceService#6
- [ ] Task 6: Implement authorization.

# Test Cases:

- [ ] **Case 1:** Verify that the searching and filtering options work and redirect to the detailed page.
  - Prerequisites: User is logged in as an admin. Admin is navigated to the "All Invoices" page. There is at least one invoice in the system
- Steps:
  - Choose the "Invoice ID" option on the search bar.
  - Search for an invoice by it's ID.
- Expected Results:
  - Redirection to the correct invoice's "Details" page. 

# Activity Diagram
![Image](https://github.com/user-attachments/assets/d2d3077f-8426-4e68-96f4-ac4db1751d92)
