### ISSUE TITLE
As an admin, I want to be able to edit an invoice so that I can correct any mistakes.

### ISSUE THREAD

**Issue by JohnoAlm** [KYH-Net23/InvoiceProvider#32]
**Made by Hossén & Oliver**

# Acceptance Criteria:

- [ ] The admin should be able to modify key details such as
  - Date
  - Due Date
  - Amount
  - Status
- [ ] All fields have validation to prevent invalid entries.
- [ ] There should be “Save” and “Cancel” buttons.
- [ ] When pressing “Save” or “Cancel”, a confirmation prompt should appear, asking the admin to confirm before continuing.
- [ ] The change should be added to a log.

# Tasks:
- [ ] Implement UI/frontend.
  - [ ] Task 1: Create a form for updating all fields.
  - [ ] Task 2: Create a "Save" button.
  - [ ] Task 3: Create a "Cancel" button.
  - [ ] Task 4: Create a confirmation prompt.
- [ ] Task 5: Implement an API endpoint for updating the invoice details.
- [ ] Task 6: Implement validation.
- [ ] Task 7: Implement logging.

# Test Cases:

- [ ] **Case 1:** Verify that the admin can edit any of the editable fields and that it updates accordingly.
  - Prerequisites: User is logged in as an admin. Admin is navigated to the "Edit invoice" page.
- Steps:
  - Change any of the fields on the “Edit invoice” page.
  - Click the "Save" button.
- Expected Results:
  - The invoice details are updated accordingly and are displayed correctly. 

# Activity Diagram
![Image](https://github.com/user-attachments/assets/d17e5aef-922c-4ca6-aec9-6f2cc445fda9)
