### ISSUE TITLE
As an admin, I want to be able to see a detailed invoice page so that I can view all relevant information about a specific invoice

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/InvoiceProvider#33]
**Made by Hossén & Oliver**

## Acceptance Criteria
- [ ] Only admins should be able to access and view invoice information.
- [ ] The page should display relevant and correct information about the Invoice
- [ ] There should be an “Edit Invoice” button on the invoice details page.
## Tasks
- [ ] KYH-Net23/AdminInvoiceService#10 
- [ ] KYH-Net23/AdminInvoiceService#9 
- [ ] KYH-Net23/AdminInvoiceService#8 
- [ ] KYH-Net23/AdminInvoiceService#7 
- [ ] Implement API endpoint for fetching an invoice from the database.
- [ ] Display the invoice information on the page.
- [ ] Implement authorization
## Test Cases
- [ ] Verify that a specific invoice’s details are correctly displayed when navigated to the ‘Details’ page
  - Prerequisites: 
    - User is logged in as an Admin.
    - User is navigated to "All Invoices" page OR to a specific order's details page.
  - Steps
    - Click on the "Details" button of a specific invoice OR the link to the invoice's details page from the order.
  - Expected result: 
    -The system redirects the admin to the details page and displays the information properly.
- [ ] Verify that an error message is received when the specific invoice’s details could not be loaded correctly
  - Prerequisites: 
    - User is logged in as an Admin.
    - User is navigated to "All Invoices" page OR to a specific order's details page.
  - Steps
    - Click on the "Details" button of a specific invoice OR the link to the invoice's details page from the order.
  - Expected result: 
    -The system displays an error message "Invoice details could not be loaded".
## Activity Diagram
![Image](https://i.imgur.com/atKH2OA.png)
