### ISSUE TITLE
As an admin, I want to view all of the invoices of a specific customer so that I can get an overview of the customers' invoices.

### ISSUE THREAD

**Issue by JohnoAlm** [KYH-Net23/InvoiceProvider#34]
**Made by Hossén & Oliver**

# Acceptance Criteria:
- [ ] The page should display a list of the customer’s invoices with relevant information

# Tasks:
- [ ] Task 1: Create an invoice data model 
- [ ] Task 2: Create an invoice view model
- [ ] Task 3: Implement a method that fetches the invoices from a database
- [ ] Task 4: Implement a method that maps the invoices from the database to the new view model
- [ ] Task 5: Implement a method that sends a request to an API and receives a response in the form of a list of invoices.
- [ ] Task 6: Implement UI/frontend

# Test Cases:

- [ ] Case 1: Verify that the list of invoices is loaded in correctly.
  - Prerequisites: 
    - User is logged in as an Admin. 
    - User is navigated to a specific Customer’s “Invoice History” page.
    - The customer has at least one invoice.
  - Steps
    - Navigate to the "Invoice History" page. 
  - Expected result: 
    - The system displays an up to date list of the specific customer’s invoices.
    
- [ ] Case 2: Verify that the correct error message is received when the specific customer doesn’t have any invoices
  - Prerequisites:
    - User is logged in as an Admin. 
    - User is navigated to a specific Customer’s “Invoice History” page.
    - The customer doesn't have any invoices OR the API/microservice for fetching invoices is offline or not working.
  - Steps:
      - Navigate to the "Invoice History" page.
  - Expected results:
      - The system displays an error message saying "No invoices available for this customer".
      
## Activity Diagram
![Image](https://github.com/user-attachments/assets/8a05fbb9-c669-43ea-883d-c9a838ab1509)
